{#- ----------------------------------------------------------------------------------------------------------
  This macro generates the SQL for a dimension table.
  It takes the following parameters:
  - staging_table: the name of the staging table
  - biz_key: the business key column(s) to use to generate the surrogate key
  - dw_key: the name of the surrogate key column
  - hash_biz_key: whether to hash the business key to generate the surrogate key
  - expose_biz_key: whether to expose the business key in the dimension table

  The macro returns:
    SQL generated that creates a dimension table from the staging table
    with the specified business key column(s) to make the surrogate key column

-#}
{%- macro generate_dimension_table_as_sql(staging_table, biz_key, dw_key, hash_biz_key, expose_biz_key, default_key = "0") %}
{{- debug("generate_dimension_table_as_sql", info=True) }}
{{- debug("staging_table: " ~ staging_table, info=True) }}
{%- if not execute %}
{{ return(dbt_utils.stage_sql(staging_table)) }}
{%- endif %}
{{- debug("biz_key: " ~ biz_key, info=True) }}
{{- debug("dw_key: " ~ dw_key, info=True) }}
{{- debug("hash_biz_key: " ~ hash_biz_key, info=True) }}
{{- debug("expose_biz_key: " ~ expose_biz_key, info=True) }}

{%- if biz_key is not string and biz_key is iterable %}
{%- set col_length = biz_key | length -%}
{%- else %}
{%- set biz_key = [ biz_key ] %}
{%- set col_length = 1 %}
{%- endif %}

-- SQL generated by generate_dimension_table_as_sql() macro
-- Creates a dimension table `{{ this.identifier }}` from staging table `{{ staging_table }}`
-- Having business key column(s) `{{ biz_key|join("`, `") }}` to make the surrogate key column `{{ dw_key }}`
--

with staging as (
  {{ dbt_utils.stage_sql(staging_table) }}
),
unknown as (
  {{ dbt_utils.unknown( staging_table, id_col_list=biz_key ) }}
),
staging_unknown as (
  select staging.*, 'normal' as dim_row_type from staging
  union all
  select unknown.*, 'unknown' as dim_row_type from unknown
),
keyed as (
  select
    {%- if col_length == 0 %}
    -- No business key column specified to generate the Surrogate key
    {{    dbt_utils.star(staging_table) }}

    {%- elif hash_biz_key == True %}
    -- {% if col_length > 1 -%}Compound business key{%- else -%}Business key{% endif %} using hash to generate the Surrogate key
    {{    dbt_utils.generate_surrogate_key(biz_key) }} as {{ dw_key }}
    {%- else %} {# Do not use hash on surrogate keys #}
    -- {% if col_length > 1 -%}Compound business key using hash{%- else -%}Business key{% endif %} to generate the Surrogate key
    {%-   if col_length == 1 %}
    {#-      unpack the list of a single biz key and do not use hash #}
    COALESCE({{      biz_key | join() }},{{default_key}}) as {{ dw_key -}}

    {%-   else %} {# Strategy for multi-column business key #}
    -- When a key is a compound of multi-column business keys, we will hash it to generate the surrogate key
    {{    dbt_utils.generate_surrogate_key(biz_key) }} as {{ dw_key }}
    {%-   endif %}
    {%- endif -%}, {# End of Surrogate Key #}
    -- Attribute columns
    {%- if expose_biz_key == True %}
    {{ '"' ~ biz_key | join('", "') ~ '"' }}, -- Include business key columns
    {#-    dbt_utils.star(staging_table, except=biz_key) #}
    {{    dbt_utils.star(staging_table, except=biz_key, indent="  ") }}
    {%- else %}
    -- Exclude business key columns ({{ biz_key|join(", ") }})
    {#-    dbt_utils.star(staging_table, except=biz_key) #}
    {{    dbt_utils.star(staging_table, except=biz_key, indent="  ") }}
    {%- endif %},
    -- Run Timestamp
    {{ dbt_utils.dw_updated_at() }}
  from staging_unknown
)
select * from keyed
{% endmacro %}
